export const refs = {
  moviesList: document.querySelector('.movie__list'),
  form: document.querySelector('.form'),
  formInput: document.querySelector('.form__input'),
  notification: document.querySelector('.notification'),
  loader: document.querySelector('.loader'),
  overlay: document.querySelector('.overlay'),
  modal: document.querySelector('.modal'),
  filmOverlay: document.querySelector('.film__overlay'),
  searchForm: document.querySelector('.form'),
  paginationNumbers: document.querySelector('.pagination-numbers'),
  paginationContainer: document.querySelector('.pagination-container'),
  nextButton: document.querySelector('.pagination-container__next-button'),
  prevButton: document.querySelector('.pagination-container__prev-button'),
};
